import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "react-bootstrap/Button";
import NavigationBarTop from "../components/NavigationBarTop";
import ModulOne from "../components/ModulOne";
import ModulTwo from "../components/ModulTwo";
import ModulThree from "../components/ModulThree";
import ModulFour from "../components/ModulFour";
import ModulFive from "../components/ModulFive";
import Footer from "../components/Footer";

export default function Home() {
 return (
  <>
   <NavigationBarTop />
   <div className={styles.container}>
    <Head>
     <title>Yayasan Fajar Qolbi</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
     <h1 className={styles.title}>
      Welcome to <a href="https://nextjs.org">Next.js!</a>
     </h1>

     <ModulOne />
     <ModulTwo />
     <ModulThree />
     <ModulFour />
     <ModulFive />
    </main>

    <footer className={styles.footer}>
     <Footer />
    </footer>
   </div>
  </>
 );
}
